name: Update test coverage
on: workflow_dispatch
jobs:
  update-cov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - run: git lfs install && git lfs pull

      - name: Python setup with dependency caching
        run: pip install pytest pytest-cov pytest-mock genbadge[coverage] torch numpy accelerate ipykernel ipython transformers 

      - name: Run pytest--cov
        shell: bash
        run: pytest --cov-report xml:reports/coverage/coverage.xml --cov-report html:reports/coverage/html_report --cov=att_viz

      - name: Run genbadge
        shell: bash
        run: genbadge coverage -i reports/coverage/coverage.xml -o reports/coverage/coverage_badge.svg

      - name: Commit and push changes
        shell: bash
        run: | # https://stackoverflow.com/a/78163451
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f reports/coverage/coverage.xml reports/coverage/html_report/* reports/coverage/coverage_badge.svg
          git restore --staged test/test_result.html test/test_attention_matrix.pickle
          git commit -m "Update coverage results"
          git push